# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


jamie = User.create(username: "jamie", password: "jamie")

puts "created Jamie"

key_string = SecureRandom.alphanumeric(8)

    
list_one = List.create(name: "Example List", urlindex:key_string)

Right.create(user:User.first, list: list_one)

puts "created list one"

list_one_items = [
    {name: 'burgers', category: 'Meat'}, 
    {name: 'sausages', category: 'Meat'}, 
    {name: 'burger buns', category: 'Bread'}, 
    {name: 'lettuce', category: 'Produce'},
    {name: 'tomatoes', category: 'Produce'},
]

list_one_items.each{|item|
    Item.create(list: list_one, name:item[:name], category:item[:category])
}

puts "added items to list one."


products = [
    {name: 'Toothpaste', category: 'Pharmacy'}, 
    {name: 'Painkillers', category: 'Pharmacy'}, 
    {name: 'Shampoo', category: 'Pharmacy'}, 
    {name: 'Shower Gel', category: 'Pharmacy'}, 
    {name: 'Soap', category: 'Pharmacy'}, 
    {name: 'Toothbrushes', category: 'Pharmacy'}, 
    {name: 'Hairbands', category: 'Pharmacy'}, 
    {name: 'paracetamol', category: 'Pharmacy'}, 
    {name: 'Ibuprofen', category: 'Pharmacy'}, 
    {name: 'aspirin', category: 'Pharmacy'}, 
    {name: 'antihistamines', category: 'Pharmacy'}, 
    {name: 'plasters', category: 'Pharmacy'}, 
    {name: 'Hair Bands', category: 'Pharmacy'}, 
    {name: 'conditioner', category: 'Pharmacy'}, 
    {name: 'moisturizer', category: 'Pharmacy'}, 
    {name: 'razor', category: 'Pharmacy'}, 
    {name: 'make up remover', category: 'Pharmacy'}, 
    {name: 'cotton pads', category: 'Pharmacy'}, 
    {name: 'cutton buds', category: 'Pharmacy'}, 
    {name: 'tampons', category: 'Pharmacy'}, 
    {name: 'pads', category: 'Pharmacy'}, 
    {name: 'Bread', category: 'Bread'}, 
    {name: 'Muffins', category: 'Bread'}, 
    {name: 'Bagels', category: 'Bread'}, 
    {name: 'crumpets', category: 'Bread'}, 
    {name: 'wraps', category: 'Bread'}, 
    {name: 'burger buns', category: 'Bread'}, 
    {name: 'rolls', category: 'Bread'}, 
    {name: 'hot dog buns', category: 'Bread'}, 
    {name: 'pitta bread', category: 'Bread'}, 
    {name: 'bananas', category: 'Produce'}, 
    {name: 'apples', category: 'Produce'}, 
    {name: 'peppers', category: 'Produce'}, 
    {name: 'spinach', category: 'Produce'}, 
    {name: 'watercress', category: 'Produce'}, 
    {name: 'ginger', category: 'Produce'}, 
    {name: 'chillies', category: 'Produce'}, 
    {name: 'tomatoes', category: 'Produce'}, 
    {name: 'spring onions', category: 'Produce'}, 
    {name: 'oranges', category: 'Produce'}, 
    {name: 'raspberries', category: 'Produce'}, 
    {name: 'blueberries', category: 'Produce'}, 
    {name: 'strawberries', category: 'Produce'}, 
    {name: 'lemons', category: 'Produce'}, 
    {name: 'limes', category: 'Produce'}, 
    {name: 'pineapples', category: 'Produce'}, 
    {name: 'mangoes', category: 'Produce'}, 
    {name: 'papayas', category: 'Produce'}, 
    {name: 'basil', category: 'Produce'}, 
    {name: 'mint', category: 'Produce'}, 
    {name: 'chives', category: 'Produce'}, 
    {name: 'onions', category: 'Produce'}, 
    {name: 'potatoes', category: 'Produce'}, 
    {name: 'courgettes', category: 'Produce'}, 
    {name: 'aubergines', category: 'Produce'}, 
    {name: 'broccoli', category: 'Produce'}, 
    {name: 'green beans', category: 'Produce'}, 
    {name: 'fine beans', category: 'Produce'}, 
    {name: 'mushrooms', category: 'Produce'}, 
    {name: 'garlic', category: 'Produce'}, 
    {name: 'rocket', category: 'Produce'}, 
    {name: 'lemongrass', category: 'Produce'}, 
    {name: 'cherries', category: 'Produce'}, 
    {name: 'spaghetti', category: 'Pasta'}, 
    {name: 'pasta', category: 'Pasta'}, 
    {name: 'lasagne', category: 'Pasta'}, 
    {name: 'lasagna', category: 'Pasta'}, 
    {name: 'pasta sauce', category: 'Pasta'}, 
    {name: 'Flour', category: 'Baking'}, 
    {name: 'Baking powder', category: 'Baking'}, 
    {name: 'Oat milk', category: 'Baking'}, 
    {name: 'Pecans', category: 'Baking'}, 
    {name: 'Salted caramel', category: 'Baking'}, 
    {name: 'Chocolate', category: 'Baking'}, 
    {name: 'walnuts', category: 'Baking'}, 
    {name: 'seeds', category: 'Baking'}, 
    {name: 'tinned fruit', category: 'Baking'}, 
    {name: 'cocoa', category: 'Baking'}, 
    {name: 'sugar', category: 'Baking'}, 
    {name: 'brown sugar', category: 'Baking'}, 
    {name: 'light brown sugar', category: 'Baking'}, 
    {name: 'dark brown sugar', category: 'Baking'}, 
    {name: 'demerara sugar', category: 'Baking'}, 
    {name: 'granulated sugar', category: 'Baking'}, 
    {name: 'caster sugar', category: 'Baking'}, 
    {name: 'icing sugar', category: 'Baking'}, 
    {name: 'food coloring', category: 'Baking'}, 
    {name: 'sprinkles', category: 'Baking'}, 
    {name: 'hundreds and thousands', category: 'Baking'}, 
    {name: 'candles', category: 'Baking'}, 
    {name: 'poppy seeds', category: 'Baking'}, 
    {name: 'sesame seeds', category: 'Baking'}, 
    {name: 'sunflower seeds', category: 'Baking'}, 
    {name: 'pumpkin seeds', category: 'Baking'}, 
    {name: 'Eggs', category: 'Baking'}, 
    {name: 'tinned tomatoes', category: 'Canned Goods'}, 
    {name: 'kidney beans', category: 'Canned Goods'}, 
    {name: 'black beans', category: 'Canned Goods'}, 
    {name: 'passata', category: 'Canned Goods'}, 
    {name: 'olives', category: 'Canned Goods'}, 
    {name: 'chickpeas', category: 'Canned Goods'}, 
    {name: 'roast peppers', category: 'Canned Goods'}, 
    {name: 'sundried tomatoes', category: 'Canned Goods'}, 
    {name: 'beef', category: 'Meat'}, 
    {name: 'chicken', category: 'Meat'}, 
    {name: 'mince', category: 'Meat'}, 
    {name: 'lamb', category: 'Meat'}, 
    {name: 'burgers', category: 'Meat'}, 
    {name: 'sausages', category: 'Meat'}, 
    {name: 'pepperoni', category: 'Meat'}, 
    {name: 'turkey', category: 'Meat'}, 
    {name: 'chicken breasts', category: 'Meat'}, 
    {name: 'chicken thighs', category: 'Meat'}, 
    {name: 'smoked salmon', category: 'Meat'}, 
    {name: 'kippers', category: 'Meat'}, 
    {name: 'cod', category: 'Meat'}, 
    {name: 'salmon', category: 'Meat'}, 
    {name: 'bacon', category: 'Meat'}, 
    {name: 'Pizza', category: 'Prepared food'}, 
    {name: 'curry', category: 'Prepared food'}, 
    {name: 'ready meals', category: 'Prepared food'}, 
    {name: 'sausage rolls', category: 'Prepared food'}, 
    {name: 'Falafels', category: 'Prepared food'}, 
    {name: 'Pies', category: 'Prepared food'}, 
    {name: 'pasties', category: 'Prepared food'}, 
    {name: 'ravioli', category: 'Prepared food'}, 
    {name: 'garlic food', category: 'Prepared food'}, 
    {name: 'cheese', category: 'Cheese'}, 
    {name: 'parmesan', category: 'Cheese'}, 
    {name: 'mozzarella', category: 'Cheese'}, 
    {name: 'cheddar', category: 'Cheese'}, 
    {name: 'gouda', category: 'Cheese'}, 
    {name: 'comte', category: 'Cheese'}, 
    {name: 'brie', category: 'Cheese'}, 
    {name: 'Double cream', category: 'Cheese'}, 
    {name: 'Cream cheese', category: 'Cheese'}, 
    {name: 'quark', category: 'Cheese'}, 
    {name: 'stilton', category: 'Cheese'}, 
    {name: 'garlic cheese', category: 'Cheese'}, 
    {name: 'boursin', category: 'Cheese'}, 
    {name: 'babybel', category: 'Cheese'}, 
    {name: 'dairylea', category: 'Cheese'}, 
    {name: 'philadelphia', category: 'Cheese'}, 
    {name: 'paneer', category: 'Cheese'}, 
    {name: 'halloumi', category: 'Cheese'}, 
    {name: 'feta', category: 'Cheese'}, 
    {name: 'ricotta', category: 'Cheese'}, 
    {name: 'edam', category: 'Cheese'}, 
    {name: 'red leicester', category: 'Cheese'}, 
    {name: 'camembert', category: 'Cheese'}, 
    {name: 'cottage cheese', category: 'Cheese'}, 
    {name: 'pecorino', category: 'Cheese'}, 
    {name: 'mascarpone', category: 'Cheese'}, 
    {name: 'burger cheese', category: 'Cheese'}, 
    {name: 'cheese slices', category: 'Cheese'}, 
    {name: 'gruyere', category: 'Cheese'}, 
    {name: 'smoked cheese', category: 'Cheese'}, 
    {name: 'Manchego', category: 'Cheese'}, 
    {name: 'Gluten-free bread', category: 'Free-From'}, 
    {name: 'Non-dairy chocolate', category: 'Free-From'}, 
    {name: 'Corn snacks', category: 'Free-From'}, 
    {name: 'Protein bars', category: 'Free-From'}, 
    {name: 'Gluten-free pasta', category: 'Free-From'}, 
    {name: 'Oatly cream', category: 'Free-From'}, 
    {name: 'juice', category: 'Juice and Dairy'}, 
    {name: 'milk', category: 'Juice and Dairy'}, 
    {name: 'butter', category: 'Juice and Dairy'}, 
    {name: 'yoghurt', category: 'Juice and Dairy'}, 
    {name: 'lacto-free', category: 'Juice and Dairy'}, 
    {name: 'goat milk', category: 'Juice and Dairy'}, 
    {name: 'pineapple juice', category: 'Juice and Dairy'}, 
    {name: 'orange juice', category: 'Juice and Dairy'}, 
    {name: 'apple juice', category: 'Juice and Dairy'}, 
    {name: 'tropical juice', category: 'Juice and Dairy'}, 
    {name: 'pear juice', category: 'Juice and Dairy'}, 
    {name: 'pastry', category: 'Juice and Dairy'}, 
    {name: 'filo pastry', category: 'Juice and Dairy'}, 
    {name: 'puff pastry', category: 'Juice and Dairy'}, 
    {name: 'shortcrust pastry', category: 'Juice and Dairy'}, 
    {name: 'coffee', category: 'Tea and Coffee'}, 
    {name: 'tea', category: 'Tea and Coffee'}, 
    {name: 'hot chocolate', category: 'Tea and Coffee'}, 
    {name: 'ovaltine', category: 'Tea and Coffee'}, 
    {name: 'Biscuits', category: 'Tea and Coffee'}, 
    {name: 'Granulated sugar', category: 'Tea and Coffee'}, 
    {name: 'frozen peas', category: 'Frozen Foods'}, 
    {name: 'peas', category: 'Frozen Foods'}, 
    {name: 'petit pois', category: 'Frozen Foods'}, 
    {name: 'chips', category: 'Frozen Foods'}, 
    {name: 'hash browns', category: 'Frozen Foods'}, 
    {name: 'frozen pizzas', category: 'Frozen Foods'}, 
    {name: 'ice', category: 'Frozen Foods'}, 
    {name: 'frozen pies', category: 'Frozen Foods'}, 
    {name: 'chicken steaks', category: 'Frozen Foods'}, 
    {name: 'chicken kiev', category: 'Frozen Foods'}, 
    {name: 'frozen fruit', category: 'Frozen Foods'}, 
    {name: 'ice cream', category: 'Frozen Foods'}, 
    {name: 'parathas', category: 'Frozen Foods'}, 
    {name: 'frozen snacks', category: 'Frozen Foods'}, 
    {name: 'fish fingers', category: 'Frozen Foods'}, 
    {name: 'battered fish', category: 'Frozen Foods'}, 
    {name: 'battered cod', category: 'Frozen Foods'}, 
    {name: 'cereal', category: 'Cereal'}, 
    {name: 'corn flakes', category: 'Cereal'}, 
    {name: 'rice krispies', category: 'Cereal'}, 
    {name: 'bran flakes', category: 'Cereal'}, 
    {name: 'granola', category: 'Cereal'}, 
    {name: 'muesli', category: 'Cereal'}, 
    {name: 'porridge', category: 'Cereal'}, 
    {name: 'apricot wheats', category: 'Cereal'}, 
    {name: 'Rice', category: 'World Foods'}, 
    {name: 'Chutney', category: 'World Foods'}, 
    {name: 'curry paste', category: 'World Foods'}, 
    {name: 'red curry paste', category: 'World Foods'}, 
    {name: 'green curry paste', category: 'World Foods'}, 
    {name: 'hoi sin sauce', category: 'World Foods'}, 
    {name: 'stir fry sauce', category: 'World Foods'}, 
    {name: 'noodles', category: 'World Foods'}, 
    {name: 'brown rice', category: 'World Foods'}, 
    {name: 'bulgur wheat', category: 'World Foods'}, 
    {name: 'popcorn', category: 'World Foods'}, 
    {name: 'kaffir lime', category: 'World Foods'}, 
    {name: 'marjoram', category: 'World Foods'}, 
    {name: 'Hoisin sauce', category: 'World Foods'}, 
    {name: 'gram flour', category: 'World Foods'}, 
    {name: 'birthday cards', category: 'Non-food'}, 
    {name: 'magazines', category: 'Non-food'}, 
    {name: 'wrapping paper', category: 'Non-food'}, 
    {name: 'toys', category: 'Non-food'}, 
    {name: 'Cinnamon', category: 'Spices'}, 
    {name: 'Celery Salt', category: 'Spices'}, 
    {name: 'allspice', category: 'Spices'}, 
    {name: 'anise', category: 'Spices'}, 
    {name: 'basil', category: 'Spices'}, 
    {name: 'bay leaf', category: 'Spices'}, 
    {name: 'blue fenugreek', category: 'Spices'}, 
    {name: 'cardamom', category: 'Spices'}, 
    {name: 'coriander', category: 'Spices'}, 
    {name: 'cumin', category: 'Spices'}, 
    {name: 'curry leaf', category: 'Spices'}, 
    {name: 'cinnamon sticks', category: 'Spices'}, 
    {name: 'cayenne pepper', category: 'Spices'}, 
    {name: 'chili peppers', category: 'Spices'}, 
    {name: 'dill', category: 'Spices'}, 
    {name: 'dill seeds', category: 'Spices'}, 
    {name: 'fennel', category: 'Spices'}, 
    {name: 'fenugreek', category: 'Spices'}, 
    {name: 'garlic salt', category: 'Spices'}, 
    {name: 'chopped garlic', category: 'Spices'}, 
    {name: 'ground ginger', category: 'Spices'}, 
    {name: 'lavender', category: 'Spices'}, 
    {name: 'oregano', category: 'Spices'}, 
    {name: 'stock', category: 'Spices'}, 
    {name: 'gravy', category: 'Spices'}, 
    {name: 'paprika', category: 'Spices'}, 
    {name: 'parsley', category: 'Spices'}, 
    {name: 'pepper', category: 'Spices'}, 
    {name: 'salt', category: 'Spices'}, 
    {name: 'fancy salt', category: 'Spices'}, 
    {name: 'saffron', category: 'Spices'}, 
    {name: 'thyme', category: 'Spices'}, 
    {name: 'tarragon', category: 'Spices'}, 
    {name: 'turmeric', category: 'Spices'}, 
    {name: 'wasabi', category: 'Spices'}, 
    {name: 'rosemary', category: 'Spices'}, 
    {name: 'Mustard', category: 'condiments'}, 
    {name: 'Ketchup', category: 'condiments'}, 
    {name: 'mayonnaise', category: 'condiments'}, 
    {name: 'sriracha', category: 'condiments'}, 
    {name: 'garlic sauce', category: 'condiments'}, 
    {name: 'bbq sauce', category: 'condiments'}, 
    {name: 'horseradish', category: 'condiments'}, 
    {name: 'brown sauce', category: 'condiments'}, 
    {name: 'baked beans', category: 'tinned foods'}, 
    {name: 'spaghetti hoops', category: 'tinned foods'}, 
    {name: 'pasta shapes', category: 'tinned foods'}, 
    {name: 'mushy peas', category: 'tinned foods'}, 
    {name: 'pease pudding', category: 'tinned foods'}, 
    {name: 'biscuits', category: 'crips and snacks'}, 
    {name: 'crisps', category: 'crips and snacks'}, 
    {name: 'doritos', category: 'crips and snacks'}, 
    {name: 'salsa', category: 'crips and snacks'}, 
    {name: 'popcorn', category: 'crips and snacks'}, 
    {name: 'hobnobs', category: 'crips and snacks'}, 
    {name: 'digestives', category: 'crips and snacks'}, 
    {name: 'coke', category: 'Soft Drinks'}, 
    {name: 'squash', category: 'Soft Drinks'}, 
    {name: 'lemonade', category: 'Soft Drinks'}, 
    {name: 'diet coke', category: 'Soft Drinks'}, 
    {name: 'orangeade', category: 'Soft Drinks'}, 
    {name: 'cordial', category: 'Soft Drinks'}, 
    {name: 'vodka', category: 'Spirits and Mixers'}, 
    {name: 'gin', category: 'Spirits and Mixers'}, 
    {name: 'amaretto', category: 'Spirits and Mixers'}, 
    {name: 'tequila', category: 'Spirits and Mixers'}, 
    {name: 'cachaca', category: 'Spirits and Mixers'}, 
    {name: 'rum', category: 'Spirits and Mixers'}, 
    {name: 'whisky', category: 'Spirits and Mixers'}, 
    {name: 'scotch', category: 'Spirits and Mixers'}, 
    {name: 'bourbon', category: 'Spirits and Mixers'}, 
    {name: 'cognac', category: 'Spirits and Mixers'}, 
    {name: 'cherry', category: 'Spirits and Mixers'}, 
    {name: 'jagermeister', category: 'Spirits and Mixers'}, 
    {name: 'brandy', category: 'Spirits and Mixers'}, 
    {name: 'tonic', category: 'Spirits and Mixers'}, 
    {name: 'soda water', category: 'Spirits and Mixers'}, 
    {name: 'red wine', category: 'Beer and Wine'}, 
    {name: 'white wine', category: 'Beer and Wine'}, 
    {name: 'champagne', category: 'Beer and Wine'}, 
    {name: 'beer', category: 'Beer and Wine'}, 
    {name: 'guiness', category: 'Beer and Wine'}, 
    {name: 'cider', category: 'Beer and Wine'}, 
    {name: 'pear cider', category: 'Beer and Wine'}, 
    {name: 'fruit cider', category: 'Beer and Wine'}, 
    {name: 'Toilet paper', category: 'Household'}, 
    {name: 'Loo roll', category: 'Household'}, 
    {name: 'kitchen roll', category: 'Household'}, 
    {name: 'kitchen paper', category: 'Household'}, 
    {name: 'sponges', category: 'Household'}, 
    {name: 'washing up gloves', category: 'Household'}, 
    {name: 'washing up liquid', category: 'Household'}, 
    {name: 'detergent', category: 'Household'}, 
    {name: 'laundry detergent', category: 'Household'}, 
    {name: 'bleach', category: 'Household'}, 
    {name: 'fabric conditioner', category: 'Household'}, 
    {name: 'scourers', category: 'Household'}, 
    {name: 'jay cloths', category: 'Household'}, 
    {name: 'bin bags', category: 'Household'}, 
    {name: 'cling film', category: 'Household'}, 
    {name: 'baking paper', category: 'Household'}, 
    {name: 'foil', category: 'Household'}, 
    {name: 'aluminium foil', category: 'Household'}, 
    {name: 'tin foil', category: 'Household'}, 
    {name: 'greaseproof paper', category: 'Household'}, 
    {name: 'dog food', category: 'Pets'}, 
    {name: 'cat food', category: 'Pets'}, 
    {name: 'dog treats', category: 'Pets'}, 
    {name: 'cat treats', category: 'Pets'}, 
    {name: 'rabbit food', category: 'Pets'}, 
    {name: 'cat litter', category: 'Pets'}, 
    {name: 'pet bedding', category: 'Pets'}, 
    {name: 'rabbit bedding', category: 'Pets'}, 
    {name: 'dog toys', category: 'Pets'}, 
    {name: 'cat toys', category: 'Pets'}, 
    {name: 'catnip', category: 'Pets'}, 
    {name: 'nappies', category: 'Baby'}, 
    {name: 'baby formula', category: 'Baby'}, 
    {name: 'nappy rash cream', category: 'Baby'}, 
    {name: 'dummy', category: 'Baby'},

]

products.each{|item|
    item[:name] = item[:name].downcase
    item[:category] = item[:category].capitalize
}

Exampleitem.create(products)

puts "imported products"

